### ISSUE TITLE
方便介绍一下在aws-sdk-php基础上做了哪些增强么？

### ISSUE THREAD

**Issue by yanhuixie** [klinson/aws-s3-minio#1]
喜闻乐见。
之前我也用minio和aws-sdk-php还有flysystem做过试验，因为验证都问题解决不了，时间关系就丢一边了。
aws-sdk-php的逻辑相当复杂，我没有详细研究，貌似确实不能直接兼容minio。
不知道您在aws-sdk-php基础上做了哪些增强或改进？或者介绍一下这个repo的缘起？
非常感谢。

**Comment by klinson** [comment]
如你所说，`minio`没有官方`sdk`，而是推荐了`aws-sdk-php`。而`aws-sdk-php`中的内容非常多，`minio`使用起来功能相当简单，很多`aws`中的`s3`的方法，在`minio`中是用不了或者用不上，`aws-sdk-php`用起来就相当不便。
所以我只是对一些`minio`常用的方法进行封装，只是想做一个好用的`minio-sdk`来用
你遇到的验证问题，应该是没有开启配置`use_path_style_endpoint`，如我的初始化`s3`客户端代码如下
```
$this->S3Client = new S3Client([
    'credentials' => [
        'key'    => $config['key'] ?? '',
        'secret' => $config['secret'] ?? '',
    ],
    'region' => $config['region'] ?? '',
    'version' => $config['version'] ?? '',
    'endpoint' => $config['endpoint'] ?? '',
    'use_path_style_endpoint' => true, //minio必须开启
]);
```

**Comment by klinson** [comment]
也欢迎大家一起来完善好这个轮子，毕竟目前`minio`专用`sdk`就仅有我这个简陋版

**Comment by soopsle** [comment]
1.3.1 导入依赖
aws/aws-sdk-php": "3.173.19 getObjectUrl ok (win10)
aws/aws-sdk-php": "3.175.0  getObjectUrl wrong (centos7)
其他方法还没测
